import json
from typing import List, Dict, Any

def get_base_twenty_problems() -> List[Dict[str, Any]]:
    """Returns the 20 base benchmark problems with enhanced fields."""
    return [
        {
            "task_id": "CUSTOM/001",
            "name": "is_palindrome",
            "entry_point": "is_palindrome",
            "category": "Strings",
            "difficulty": "Easy",
            "prompt": "def is_palindrome(s: str) -> bool:\n    \"\"\"Checks if a string is a palindrome, ignoring casing and non-alphanumerics.\"\"\"\n",
            "requirement": "Write a python function `is_palindrome(s: str) -> bool` that returns True if a given string is a palindrome, ignoring casing and non-alphanumeric characters, and False otherwise.",
            "canonical_solution": "def is_palindrome(s: str) -> bool:\n    cleaned = [c.lower() for c in s if c.isalnum()]\n    return cleaned == cleaned[::-1]",
            "constraints": ["0 <= len(s) <= 2 * 10^5", "String consists of printable ASCII characters"],
            "expected_output": "Boolean True if palindrome, False otherwise",
            "edge_cases": ["Empty string returns True", "Single char returns True", "Mixed casing with punctuation"],
            "common_errors": ["Forgetting to lowercase characters", "Not filtering punctuation"],
            "error_type": ["edge_case_error", "logical_error"],
            "buggy_solution": "def is_palindrome(s: str) -> bool:\n    # Bug: does not ignore non-alphanumeric characters\n    s_lower = s.lower()\n    return s_lower == s_lower[::-1]",
            "buggy_error": "AssertionError: Fails on strings with spaces or punctuation like 'A man, a plan, a canal: Panama'",
            "repair_hint": "Filter out non-alphanumeric characters using c.isalnum() before reversing comparison.",
            "repaired_solution": "def is_palindrome(s: str) -> bool:\n    cleaned = [c.lower() for c in s if c.isalnum()]\n    return cleaned == cleaned[::-1]",
            "test": "def check(candidate):\n    assert candidate('A man, a plan, a canal: Panama') == True\n    assert candidate('race a car') == False\n    assert candidate('') == True\n    assert candidate('0P') == False\n    assert candidate('ab_a') == True",
            "test_code": "assert is_palindrome('A man, a plan, a canal: Panama') == True\nassert is_palindrome('race a car') == False\nassert is_palindrome('') == True\nassert is_palindrome('0P') == False\nassert is_palindrome('ab_a') == True",
            "test_cases": [
                {"input": "A man, a plan, a canal: Panama", "expected": "True", "type": "normal"},
                {"input": "race a car", "expected": "False", "type": "normal"},
                {"input": "", "expected": "True", "type": "edge_case"}
            ]
        },
        {
            "task_id": "CUSTOM/002",
            "name": "valid_anagram",
            "entry_point": "valid_anagram",
            "category": "Strings",
            "difficulty": "Easy",
            "prompt": "def valid_anagram(s: str, t: str) -> bool:\n    \"\"\"Checks if t is an anagram of s.\"\"\"\n",
            "requirement": "Write a python function `valid_anagram(s: str, t: str) -> bool` that returns True if `t` is an anagram of `s`, and False otherwise.",
            "canonical_solution": "from collections import Counter\ndef valid_anagram(s: str, t: str) -> bool:\n    return Counter(s) == Counter(t)",
            "constraints": ["1 <= len(s), len(t) <= 5 * 10^4", "Lowercase English letters"],
            "expected_output": "True if identical character frequencies, False otherwise",
            "edge_cases": ["Strings of different lengths", "Identical single characters"],
            "common_errors": ["Comparing set(s) == set(t) ignoring duplicate character frequencies"],
            "error_type": ["logical_error"],
            "buggy_solution": "def valid_anagram(s: str, t: str) -> bool:\n    # Bug: set comparison ignores character counts\n    return set(s) == set(t)",
            "buggy_error": "AssertionError: Fails for strings with same unique characters but different counts",
            "repair_hint": "Use collections.Counter or sorted() to compare character frequencies.",
            "repaired_solution": "from collections import Counter\ndef valid_anagram(s: str, t: str) -> bool:\n    return Counter(s) == Counter(t)",
            "test": "def check(candidate):\n    assert candidate('anagram', 'nagaram') == True\n    assert candidate('rat', 'car') == False\n    assert candidate('a', 'a') == True\n    assert candidate('ab', 'a') == False\n    assert candidate('aab', 'abb') == False",
            "test_code": "assert valid_anagram('anagram', 'nagaram') == True\nassert valid_anagram('rat', 'car') == False\nassert valid_anagram('a', 'a') == True\nassert valid_anagram('ab', 'a') == False\nassert valid_anagram('aab', 'abb') == False",
            "test_cases": [
                {"input": "('anagram', 'nagaram')", "expected": "True", "type": "normal"},
                {"input": "('rat', 'car')", "expected": "False", "type": "normal"}
            ]
        },
        {
            "task_id": "CUSTOM/003",
            "name": "length_of_longest_substring",
            "entry_point": "length_of_longest_substring",
            "category": "Strings",
            "difficulty": "Medium",
            "prompt": "def length_of_longest_substring(s: str) -> int:\n    \"\"\"Finds length of the longest substring without repeating characters.\"\"\"\n",
            "requirement": "Write a python function `length_of_longest_substring(s: str) -> int` that finds the length of the longest substring without repeating characters.",
            "canonical_solution": "def length_of_longest_substring(s: str) -> int:\n    char_map = {}\n    left = max_len = 0\n    for right, c in enumerate(s):\n        if c in char_map and char_map[c] >= left:\n            left = char_map[c] + 1\n        char_map[c] = right\n        max_len = max(max_len, right - left + 1)\n    return max_len",
            "constraints": ["0 <= len(s) <= 5 * 10^4"],
            "expected_output": "Integer maximum length of non-repeating substring",
            "edge_cases": ["Empty string returns 0", "All identical characters returns 1", "Single space returns 1"],
            "common_errors": ["Not updating left pointer when duplicate occurs before left"],
            "error_type": ["index_error", "logical_error"],
            "buggy_solution": "def length_of_longest_substring(s: str) -> int:\n    char_map = {}\n    left = max_len = 0\n    for right, c in enumerate(s):\n        if c in char_map:\n            left = char_map[c] + 1\n        char_map[c] = right\n        max_len = max(max_len, right - left + 1)\n    return max_len",
            "buggy_error": "AssertionError: Fails when repeated character occurred before current window left pointer",
            "repair_hint": "Only advance left pointer if char_map[c] >= left.",
            "repaired_solution": "def length_of_longest_substring(s: str) -> int:\n    char_map = {}\n    left = max_len = 0\n    for right, c in enumerate(s):\n        if c in char_map and char_map[c] >= left:\n            left = char_map[c] + 1\n        char_map[c] = right\n        max_len = max(max_len, right - left + 1)\n    return max_len",
            "test": "def check(candidate):\n    assert candidate('abcabcbb') == 3\n    assert candidate('bbbbb') == 1\n    assert candidate('pwwkew') == 3\n    assert candidate('') == 0\n    assert candidate(' ') == 1\n    assert candidate('abba') == 2",
            "test_code": "assert length_of_longest_substring('abcabcbb') == 3\nassert length_of_longest_substring('bbbbb') == 1\nassert length_of_longest_substring('pwwkew') == 3\nassert length_of_longest_substring('') == 0\nassert length_of_longest_substring(' ') == 1\nassert length_of_longest_substring('abba') == 2",
            "test_cases": [
                {"input": "abcabcbb", "expected": "3", "type": "normal"},
                {"input": "", "expected": "0", "type": "edge_case"}
            ]
        },
        {
            "task_id": "CUSTOM/004",
            "name": "compress_string",
            "entry_point": "compress_string",
            "category": "Strings",
            "difficulty": "Medium",
            "prompt": "def compress_string(s: str) -> str:\n    \"\"\"Run-length encodes consecutive identical characters.\"\"\"\n",
            "requirement": "Write a python function `compress_string(s: str) -> str` that performs basic string compression using counts of repeated characters.",
            "canonical_solution": "def compress_string(s: str) -> str:\n    if not s: return ''\n    res, i = [], 0\n    while i < len(s):\n        c, count = s[i], 0\n        while i < len(s) and s[i] == c:\n            count += 1\n            i += 1\n        res.append(f'{c}{count}')\n    return ''.join(res)",
            "constraints": ["0 <= len(s) <= 10^4"],
            "expected_output": "Compressed run-length string",
            "edge_cases": ["Empty string returns ''", "All distinct characters"],
            "common_errors": ["Off-by-one index error at string boundary"],
            "error_type": ["index_error"],
            "buggy_solution": "def compress_string(s: str) -> str:\n    if not s: return ''\n    res = []\n    for i in range(len(s)):\n        if s[i] == s[i+1]: pass\n    return ''",
            "buggy_error": "IndexError: string index out of range",
            "repair_hint": "Use while loop with bounds check i < len(s) to count character runs.",
            "repaired_solution": "def compress_string(s: str) -> str:\n    if not s: return ''\n    res, i = [], 0\n    while i < len(s):\n        c, count = s[i], 0\n        while i < len(s) and s[i] == c:\n            count += 1\n            i += 1\n        res.append(f'{c}{count}')\n    return ''.join(res)",
            "test": "def check(candidate):\n    assert candidate('aabcccccaaa') == 'a2b1c5a3'\n    assert candidate('') == ''\n    assert candidate('abc') == 'a1b1c1'\n    assert candidate('a') == 'a1'",
            "test_code": "assert compress_string('aabcccccaaa') == 'a2b1c5a3'\nassert compress_string('') == ''\nassert compress_string('abc') == 'a1b1c1'\nassert compress_string('a') == 'a1'",
            "test_cases": [{"input": "aabcccccaaa", "expected": "a2b1c5a3", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/005",
            "name": "two_sum",
            "entry_point": "two_sum",
            "category": "Arrays",
            "difficulty": "Easy",
            "prompt": "def two_sum(nums: list[int], target: int) -> list[int]:\n    \"\"\"Returns 0-based indices of two numbers that add up to target.\"\"\"\n",
            "requirement": "Write a python function `two_sum(nums: list[int], target: int) -> list[int]` that returns 0-based indices of the two numbers such that they add up to target.",
            "canonical_solution": "def two_sum(nums: list[int], target: int) -> list[int]:\n    seen = {}\n    for i, num in enumerate(nums):\n        comp = target - num\n        if comp in seen:\n            return [seen[comp], i]\n        seen[num] = i\n    return []",
            "constraints": ["2 <= len(nums) <= 10^4", "-10^9 <= nums[i] <= 10^9"],
            "expected_output": "List of two indices [i, j]",
            "edge_cases": ["Negative numbers", "Duplicate identical values adding to target"],
            "common_errors": ["Reusing the same element twice (e.g. nums[i] * 2 == target)"],
            "error_type": ["logical_error"],
            "buggy_solution": "def two_sum(nums: list[int], target: int) -> list[int]:\n    for i in range(len(nums)):\n        for j in range(len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]\n    return []",
            "buggy_error": "AssertionError: Returns same element index [i, i] when target == 2 * nums[i]",
            "repair_hint": "Ensure j > i or use a hash map populated as you iterate to prevent using the same element index twice.",
            "repaired_solution": "def two_sum(nums: list[int], target: int) -> list[int]:\n    seen = {}\n    for i, num in enumerate(nums):\n        comp = target - num\n        if comp in seen:\n            return [seen[comp], i]\n        seen[num] = i\n    return []",
            "test": "def check(candidate):\n    assert candidate([2, 7, 11, 15], 9) == [0, 1]\n    assert candidate([3, 2, 4], 6) == [1, 2]\n    assert candidate([3, 3], 6) == [0, 1]",
            "test_code": "assert two_sum([2, 7, 11, 15], 9) == [0, 1]\nassert two_sum([3, 2, 4], 6) == [1, 2]\nassert two_sum([3, 3], 6) == [0, 1]",
            "test_cases": [{"input": "([2, 7, 11, 15], 9)", "expected": "[0, 1]", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/006",
            "name": "move_zeroes",
            "entry_point": "move_zeroes",
            "category": "Arrays",
            "difficulty": "Easy",
            "prompt": "def move_zeroes(nums: list[int]) -> list[int]:\n    \"\"\"Moves all zeroes to end while maintaining relative order of non-zeroes.\"\"\"\n",
            "requirement": "Write a python function `move_zeroes(nums: list[int]) -> list[int]` that moves all zeroes to the end while maintaining relative order of non-zero elements.",
            "canonical_solution": "def move_zeroes(nums: list[int]) -> list[int]:\n    res = [x for x in nums if x != 0]\n    res.extend([0] * (len(nums) - len(res)))\n    return res",
            "constraints": ["1 <= len(nums) <= 10^4"],
            "expected_output": "List of integers with zeroes at end",
            "edge_cases": ["No zeroes in array", "All zeroes", "Single element 0"],
            "common_errors": ["Modifying list in-place while iterating causes skipped elements"],
            "error_type": ["index_error", "logical_error"],
            "buggy_solution": "def move_zeroes(nums: list[int]) -> list[int]:\n    # Bug: filters non-zero values but forgets to pad zeroes to original length\n    return [x for x in nums if x != 0]",
            "buggy_error": "AssertionError: Forgets to pad trailing zeroes",
            "repair_hint": "Filter non-zero elements into new list and append zeros count, or use two pointers.",
            "repaired_solution": "def move_zeroes(nums: list[int]) -> list[int]:\n    res = [x for x in nums if x != 0]\n    res.extend([0] * (len(nums) - len(res)))\n    return res",
            "test": "def check(candidate):\n    assert candidate([0, 1, 0, 3, 12]) == [1, 3, 12, 0, 0]\n    assert candidate([0]) == [0]\n    assert candidate([1, 2, 3]) == [1, 2, 3]\n    assert candidate([0, 0, 1]) == [1, 0, 0]",
            "test_code": "assert move_zeroes([0, 1, 0, 3, 12]) == [1, 3, 12, 0, 0]\nassert move_zeroes([0]) == [0]\nassert move_zeroes([1, 2, 3]) == [1, 2, 3]\nassert move_zeroes([0, 0, 1]) == [1, 0, 0]",
            "test_cases": [{"input": "[0, 1, 0, 3, 12]", "expected": "[1, 3, 12, 0, 0]", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/007",
            "name": "max_subarray_sum",
            "entry_point": "max_subarray_sum",
            "category": "Arrays",
            "difficulty": "Medium",
            "prompt": "def max_subarray_sum(nums: list[int]) -> int:\n    \"\"\"Finds maximum contiguous subarray sum (Kadane's algorithm).\"\"\"\n",
            "requirement": "Write a python function `max_subarray_sum(nums: list[int]) -> int` that finds the contiguous subarray with the largest sum and returns its sum.",
            "canonical_solution": "def max_subarray_sum(nums: list[int]) -> int:\n    max_sum = cur_sum = nums[0]\n    for x in nums[1:]:\n        cur_sum = max(x, cur_sum + x)\n        max_sum = max(max_sum, cur_sum)\n    return max_sum",
            "constraints": ["1 <= len(nums) <= 10^5", "-10^4 <= nums[i] <= 10^4"],
            "expected_output": "Integer maximum sum",
            "edge_cases": ["All negative numbers", "Single element"],
            "common_errors": ["Initializing max_sum to 0 instead of nums[0] breaks all-negative arrays"],
            "error_type": ["logical_error", "edge_case_error"],
            "buggy_solution": "def max_subarray_sum(nums: list[int]) -> int:\n    max_sum = 0\n    cur_sum = 0\n    for x in nums:\n        cur_sum = max(x, cur_sum + x)\n        max_sum = max(max_sum, cur_sum)\n    return max_sum",
            "buggy_error": "AssertionError: Fails for all-negative arrays (returns 0 instead of largest negative)",
            "repair_hint": "Initialize max_sum and cur_sum to nums[0], not 0.",
            "repaired_solution": "def max_subarray_sum(nums: list[int]) -> int:\n    max_sum = cur_sum = nums[0]\n    for x in nums[1:]:\n        cur_sum = max(x, cur_sum + x)\n        max_sum = max(max_sum, cur_sum)\n    return max_sum",
            "test": "def check(candidate):\n    assert candidate([-2, 1, -3, 4, -1, 2, 1, -5, 4]) == 6\n    assert candidate([1]) == 1\n    assert candidate([5, 4, -1, 7, 8]) == 23\n    assert candidate([-1, -2, -3]) == -1",
            "test_code": "assert max_subarray_sum([-2, 1, -3, 4, -1, 2, 1, -5, 4]) == 6\nassert max_subarray_sum([1]) == 1\nassert max_subarray_sum([5, 4, -1, 7, 8]) == 23\nassert max_subarray_sum([-1, -2, -3]) == -1",
            "test_cases": [{"input": "[-2, 1, -3, 4, -1, 2, 1, -5, 4]", "expected": "6", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/008",
            "name": "max_area",
            "entry_point": "max_area",
            "category": "Arrays",
            "difficulty": "Medium",
            "prompt": "def max_area(height: list[int]) -> int:\n    \"\"\"Container with Most Water: returns max water container can store.\"\"\"\n",
            "requirement": "Write a python function `max_area(height: list[int]) -> int` that finds two lines that together with x-axis form a container containing the most water.",
            "canonical_solution": "def max_area(height: list[int]) -> int:\n    left, right = 0, len(height) - 1\n    res = 0\n    while left < right:\n        res = max(res, min(height[left], height[right]) * (right - left))\n        if height[left] < height[right]:\n            left += 1\n        else:\n            right -= 1\n    return res",
            "constraints": ["2 <= len(height) <= 10^5"],
            "expected_output": "Integer maximum water area",
            "edge_cases": ["Two lines", "All equal heights"],
            "common_errors": ["Moving the taller pointer instead of the shorter pointer"],
            "error_type": ["logical_error"],
            "buggy_solution": "def max_area(height: list[int]) -> int:\n    left, right = 0, len(height) - 1\n    res = 0\n    while left < right:\n        res = max(res, min(height[left], height[right]) * (right - left))\n        left += 1\n    return res",
            "buggy_error": "AssertionError: Arbitrarily increments left pointer without comparing heights",
            "repair_hint": "Advance the pointer with the smaller height (if height[left] < height[right] left += 1 else right -= 1).",
            "repaired_solution": "def max_area(height: list[int]) -> int:\n    left, right = 0, len(height) - 1\n    res = 0\n    while left < right:\n        res = max(res, min(height[left], height[right]) * (right - left))\n        if height[left] < height[right]:\n            left += 1\n        else:\n            right -= 1\n    return res",
            "test": "def check(candidate):\n    assert candidate([1, 8, 6, 2, 5, 4, 8, 3, 7]) == 49\n    assert candidate([1, 1]) == 1\n    assert candidate([4, 3, 2, 1, 4]) == 16\n    assert candidate([1, 2, 1]) == 2\n    assert candidate([9, 8, 4, 3, 2, 1]) == 9",
            "test_code": "assert max_area([1, 8, 6, 2, 5, 4, 8, 3, 7]) == 49\nassert max_area([1, 1]) == 1\nassert max_area([4, 3, 2, 1, 4]) == 16\nassert max_area([1, 2, 1]) == 2\nassert max_area([9, 8, 4, 3, 2, 1]) == 9",
            "test_cases": [{"input": "[1, 8, 6, 2, 5, 4, 8, 3, 7]", "expected": "49", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/009",
            "name": "merge_intervals",
            "entry_point": "merge_intervals",
            "category": "Arrays",
            "difficulty": "Medium",
            "prompt": "def merge_intervals(intervals: list[list[int]]) -> list[list[int]]:\n    \"\"\"Merges all overlapping intervals.\"\"\"\n",
            "requirement": "Write a python function `merge_intervals(intervals: list[list[int]]) -> list[list[int]]` that merges all overlapping intervals into non-overlapping intervals.",
            "canonical_solution": "def merge_intervals(intervals: list[list[int]]) -> list[list[int]]:\n    if not intervals: return []\n    intervals.sort(key=lambda x: x[0])\n    merged = [intervals[0]]\n    for cur in intervals[1:]:\n        prev = merged[-1]\n        if cur[0] <= prev[1]:\n            prev[1] = max(prev[1], cur[1])\n        else:\n            merged.append(cur)\n    return merged",
            "constraints": ["1 <= len(intervals) <= 10^4"],
            "expected_output": "List of merged [start, end] intervals",
            "edge_cases": ["Single interval", "Already non-overlapping", "One interval fully contains another"],
            "common_errors": ["Forgetting to sort intervals before linear scan"],
            "error_type": ["logical_error"],
            "buggy_solution": "def merge_intervals(intervals: list[list[int]]) -> list[list[int]]:\n    merged = [intervals[0]]\n    for cur in intervals[1:]:\n        prev = merged[-1]\n        if cur[0] <= prev[1]:\n            prev[1] = cur[1]\n        else:\n            merged.append(cur)\n    return merged",
            "buggy_error": "AssertionError: Fails when intervals are unsorted or when second interval is shorter than first",
            "repair_hint": "Sort by start time first, and update end with max(prev[1], cur[1]).",
            "repaired_solution": "def merge_intervals(intervals: list[list[int]]) -> list[list[int]]:\n    if not intervals: return []\n    intervals.sort(key=lambda x: x[0])\n    merged = [intervals[0]]\n    for cur in intervals[1:]:\n        prev = merged[-1]\n        if cur[0] <= prev[1]:\n            prev[1] = max(prev[1], cur[1])\n        else:\n            merged.append(cur)\n    return merged",
            "test": "def check(candidate):\n    assert candidate([[1, 3], [2, 6], [8, 10], [15, 18]]) == [[1, 6], [8, 10], [15, 18]]\n    assert candidate([[1, 4], [4, 5]]) == [[1, 5]]\n    assert candidate([[1, 4], [2, 3]]) == [[1, 4]]",
            "test_code": "assert merge_intervals([[1, 3], [2, 6], [8, 10], [15, 18]]) == [[1, 6], [8, 10], [15, 18]]\nassert merge_intervals([[1, 4], [4, 5]]) == [[1, 5]]\nassert merge_intervals([[1, 4], [2, 3]]) == [[1, 4]]",
            "test_cases": [{"input": "[[1, 3], [2, 6], [8, 10], [15, 18]]", "expected": "[[1, 6], [8, 10], [15, 18]]", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/010",
            "name": "trapping_rain_water",
            "entry_point": "trapping_rain_water",
            "category": "Arrays",
            "difficulty": "Hard",
            "prompt": "def trapping_rain_water(height: list[int]) -> int:\n    \"\"\"Calculates how much water can be trapped between elevation bars.\"\"\"\n",
            "requirement": "Write a python function `trapping_rain_water(height: list[int]) -> int` that computes total water trapped after raining.",
            "canonical_solution": "def trapping_rain_water(height: list[int]) -> int:\n    if not height: return 0\n    l, r = 0, len(height) - 1\n    max_l, max_r = height[l], height[r]\n    water = 0\n    while l < r:\n        if max_l < max_r:\n            l += 1\n            max_l = max(max_l, height[l])\n            water += max_l - height[l]\n        else:\n            r -= 1\n            max_r = max(max_r, height[r])\n            water += max_r - height[r]\n    return water",
            "constraints": ["1 <= len(height) <= 2 * 10^4"],
            "expected_output": "Integer volume of trapped water",
            "edge_cases": ["Strictly ascending or descending elevations", "Less than 3 bars"],
            "common_errors": ["Failing to maintain prefix and suffix max boundaries"],
            "error_type": ["logical_error"],
            "buggy_solution": "def trapping_rain_water(height: list[int]) -> int:\n    water = 0\n    for i in range(1, len(height)-1):\n        water += min(height[i-1], height[i+1]) - height[i]\n    return max(0, water)",
            "buggy_error": "AssertionError: Only checks immediate neighbors instead of global left/right maximums",
            "repair_hint": "Use two pointers maintaining max_left and max_right boundaries.",
            "repaired_solution": "def trapping_rain_water(height: list[int]) -> int:\n    if not height: return 0\n    l, r = 0, len(height) - 1\n    max_l, max_r = height[l], height[r]\n    water = 0\n    while l < r:\n        if max_l < max_r:\n            l += 1\n            max_l = max(max_l, height[l])\n            water += max_l - height[l]\n        else:\n            r -= 1\n            max_r = max(max_r, height[r])\n            water += max_r - height[r]\n    return water",
            "test": "def check(candidate):\n    assert candidate([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) == 6\n    assert candidate([4, 2, 0, 3, 2, 5]) == 9\n    assert candidate([]) == 0\n    assert candidate([1, 2, 3]) == 0",
            "test_code": "assert trapping_rain_water([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]) == 6\nassert trapping_rain_water([4, 2, 0, 3, 2, 5]) == 9\nassert trapping_rain_water([]) == 0\nassert trapping_rain_water([1, 2, 3]) == 0",
            "test_cases": [{"input": "[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]", "expected": "6", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/011",
            "name": "is_prime",
            "entry_point": "is_prime",
            "category": "Math",
            "difficulty": "Easy",
            "prompt": "def is_prime(n: int) -> bool:\n    \"\"\"Checks if an integer n is prime.\"\"\"\n",
            "requirement": "Write a python function `is_prime(n: int) -> bool` that returns True if n is prime and False otherwise.",
            "canonical_solution": "def is_prime(n: int) -> bool:\n    if n <= 1: return False\n    if n <= 3: return True\n    if n % 2 == 0 or n % 3 == 0: return False\n    i = 5\n    while i * i <= n:\n        if n % i == 0 or n % (i + 2) == 0: return False\n        i += 6\n    return True",
            "constraints": ["-10^9 <= n <= 10^9"],
            "expected_output": "Boolean True if prime, False otherwise",
            "edge_cases": ["n <= 1 returns False", "n = 2 returns True", "n = 3 returns True"],
            "common_errors": ["Considering 1 as prime", "Negative numbers as prime"],
            "error_type": ["edge_case_error"],
            "buggy_solution": "def is_prime(n: int) -> bool:\n    # Bug: considers 1 as prime\n    if n < 1: return False\n    for i in range(2, n):\n        if n % i == 0: return False\n    return True",
            "buggy_error": "AssertionError: is_prime(1) returned True",
            "repair_hint": "Check if n <= 1: return False.",
            "repaired_solution": "def is_prime(n: int) -> bool:\n    if n <= 1: return False\n    if n <= 3: return True\n    if n % 2 == 0 or n % 3 == 0: return False\n    i = 5\n    while i * i <= n:\n        if n % i == 0 or n % (i + 2) == 0: return False\n        i += 6\n    return True",
            "test": "def check(candidate):\n    assert candidate(2) == True\n    assert candidate(3) == True\n    assert candidate(4) == False\n    assert candidate(1) == False\n    assert candidate(0) == False\n    assert candidate(-5) == False\n    assert candidate(29) == True",
            "test_code": "assert is_prime(2) == True\nassert is_prime(3) == True\nassert is_prime(4) == False\nassert is_prime(1) == False\nassert is_prime(0) == False\nassert is_prime(-5) == False\nassert is_prime(29) == True",
            "test_cases": [{"input": "2", "expected": "True", "type": "normal"}, {"input": "1", "expected": "False", "type": "edge_case"}]
        },
        {
            "task_id": "CUSTOM/012",
            "name": "count_primes",
            "entry_point": "count_primes",
            "category": "Math",
            "difficulty": "Easy",
            "prompt": "def count_primes(n: int) -> int:\n    \"\"\"Counts primes strictly less than n (Sieve of Eratosthenes).\"\"\"\n",
            "requirement": "Write a python function `count_primes(n: int) -> int` that returns the number of prime numbers strictly less than n.",
            "canonical_solution": "def count_primes(n: int) -> int:\n    if n <= 2: return 0\n    sieve = [True] * n\n    sieve[0] = sieve[1] = False\n    for i in range(2, int(n**0.5) + 1):\n        if sieve[i]:\n            sieve[i*i:n:i] = [False] * len(range(i*i, n, i))\n    return sum(sieve)",
            "constraints": ["0 <= n <= 5 * 10^6"],
            "expected_output": "Integer count of primes < n",
            "edge_cases": ["n = 0 returns 0", "n = 1 returns 0", "n = 2 returns 0"],
            "common_errors": ["Counting n itself when n is prime", "O(N^2) trial division timeout"],
            "error_type": ["edge_case_error"],
            "buggy_solution": "def count_primes(n: int) -> int:\n    # Counts primes <= n instead of strictly < n\n    if n <= 2: return 0\n    count = 0\n    for x in range(2, n + 1):\n        if all(x % i != 0 for i in range(2, int(x**0.5) + 1)):\n            count += 1\n    return count",
            "buggy_error": "AssertionError: Counts n when n is prime instead of strictly less than n",
            "repair_hint": "Loop up to n (exclusive) using Sieve of Eratosthenes.",
            "repaired_solution": "def count_primes(n: int) -> int:\n    if n <= 2: return 0\n    sieve = [True] * n\n    sieve[0] = sieve[1] = False\n    for i in range(2, int(n**0.5) + 1):\n        if sieve[i]:\n            sieve[i*i:n:i] = [False] * len(range(i*i, n, i))\n    return sum(sieve)",
            "test": "def check(candidate):\n    assert candidate(10) == 4\n    assert candidate(0) == 0\n    assert candidate(1) == 0\n    assert candidate(2) == 0\n    assert candidate(3) == 1",
            "test_code": "assert count_primes(10) == 4\nassert count_primes(0) == 0\nassert count_primes(1) == 0\nassert count_primes(2) == 0\nassert count_primes(3) == 1",
            "test_cases": [{"input": "10", "expected": "4", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/013",
            "name": "power",
            "entry_point": "power",
            "category": "Math",
            "difficulty": "Medium",
            "prompt": "def power(x: float, n: int) -> float:\n    \"\"\"Calculates x raised to power n in O(log n) time.\"\"\"\n",
            "requirement": "Write a python function `power(x: float, n: int) -> float` that computes x raised to the power n.",
            "canonical_solution": "def power(x: float, n: int) -> float:\n    if n < 0:\n        x = 1 / x\n        n = -n\n    res = 1.0\n    while n > 0:\n        if n % 2 == 1:\n            res *= x\n        x *= x\n        n //= 2\n    return round(res, 5)",
            "constraints": ["-100.0 < x < 100.0", "-2^31 <= n <= 2^31 - 1"],
            "expected_output": "Float result rounded to 5 decimal places",
            "edge_cases": ["n = 0 returns 1.0", "Negative exponent", "x = 0"],
            "common_errors": ["Not handling negative exponent n < 0"],
            "error_type": ["edge_case_error", "logical_error"],
            "buggy_solution": "def power(x: float, n: int) -> float:\n    # Bug: fails for negative exponents\n    res = 1.0\n    for _ in range(n):\n        res *= x\n    return round(res, 5)",
            "buggy_error": "AssertionError: Fails on negative exponents like power(2.0, -2)",
            "repair_hint": "If n < 0: invert x = 1 / x and negate n = -n, then use binary exponentiation.",
            "repaired_solution": "def power(x: float, n: int) -> float:\n    if n < 0:\n        x = 1 / x\n        n = -n\n    res = 1.0\n    while n > 0:\n        if n % 2 == 1:\n            res *= x\n        x *= x\n        n //= 2\n    return round(res, 5)",
            "test": "def check(candidate):\n    assert candidate(2.0, 10) == 1024.0\n    assert candidate(2.1, 3) == 9.261\n    assert candidate(2.0, -2) == 0.25\n    assert candidate(5.0, 0) == 1.0",
            "test_code": "assert power(2.0, 10) == 1024.0\nassert power(2.1, 3) == 9.261\nassert power(2.0, -2) == 0.25\nassert power(5.0, 0) == 1.0",
            "test_cases": [{"input": "(2.0, 10)", "expected": "1024.0", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/014",
            "name": "binary_search",
            "entry_point": "binary_search",
            "category": "Searching & Sorting",
            "difficulty": "Easy",
            "prompt": "def binary_search(nums: list[int], target: int) -> int:\n    \"\"\"Searches for target in ascending sorted array nums.\"\"\"\n",
            "requirement": "Write a python function `binary_search(nums: list[int], target: int) -> int` that searches for target in sorted nums and returns its index or -1 if not found.",
            "canonical_solution": "def binary_search(nums: list[int], target: int) -> int:\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target: return mid\n        elif nums[mid] < target: l = mid + 1\n        else: r = mid - 1\n    return -1",
            "constraints": ["1 <= len(nums) <= 10^4", "All elements unique and sorted"],
            "expected_output": "0-based integer index or -1",
            "edge_cases": ["Target at boundary index 0 or len - 1", "Target not in list"],
            "common_errors": ["Using l < r instead of l <= r misses single-element matches"],
            "error_type": ["logical_error", "edge_case_error"],
            "buggy_solution": "def binary_search(nums: list[int], target: int) -> int:\n    # Bug: l < r misses single-element check\n    l, r = 0, len(nums) - 1\n    while l < r:\n        mid = (l + r) // 2\n        if nums[mid] == target: return mid\n        elif nums[mid] < target: l = mid + 1\n        else: r = mid - 1\n    return -1",
            "buggy_error": "AssertionError: Misses target when target is at index r or in 1-element list",
            "repair_hint": "Use while l <= r so the loop checks when l == r.",
            "repaired_solution": "def binary_search(nums: list[int], target: int) -> int:\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target: return mid\n        elif nums[mid] < target: l = mid + 1\n        else: r = mid - 1\n    return -1",
            "test": "def check(candidate):\n    assert candidate([-1, 0, 3, 5, 9, 12], 9) == 4\n    assert candidate([-1, 0, 3, 5, 9, 12], 2) == -1\n    assert candidate([5], 5) == 0\n    assert candidate([5], -5) == -1",
            "test_code": "assert binary_search([-1, 0, 3, 5, 9, 12], 9) == 4\nassert binary_search([-1, 0, 3, 5, 9, 12], 2) == -1\nassert binary_search([5], 5) == 0\nassert binary_search([5], -5) == -1",
            "test_cases": [{"input": "([-1, 0, 3, 5, 9, 12], 9)", "expected": "4", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/015",
            "name": "search_rotated_array",
            "entry_point": "search_rotated_array",
            "category": "Searching & Sorting",
            "difficulty": "Medium",
            "prompt": "def search_rotated_array(nums: list[int], target: int) -> int:\n    \"\"\"Searches target in rotated sorted array in O(log n) time.\"\"\"\n",
            "requirement": "Write a python function `search_rotated_array(nums: list[int], target: int) -> int` that searches for target in a rotated sorted array.",
            "canonical_solution": "def search_rotated_array(nums: list[int], target: int) -> int:\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target: return mid\n        if nums[l] <= nums[mid]:\n            if nums[l] <= target < nums[mid]: r = mid - 1\n            else: l = mid + 1\n        else:\n            if nums[mid] < target <= nums[r]: l = mid + 1\n            else: r = mid - 1\n    return -1",
            "constraints": ["1 <= len(nums) <= 5000", "All elements unique"],
            "expected_output": "Integer index or -1",
            "edge_cases": ["Target at pivot point", "Array not rotated"],
            "common_errors": ["Incorrect range check on sorted half"],
            "error_type": ["logical_error"],
            "buggy_solution": "def search_rotated_array(nums: list[int], target: int) -> int:\n    # Bug: assumes array is not rotated\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target: return mid\n        elif nums[mid] < target: l = mid + 1\n        else: r = mid - 1\n    return -1",
            "buggy_error": "AssertionError: Fails when target is in the rotated segment",
            "repair_hint": "Check whether left half or right half is sorted, then check if target lies within that sorted half.",
            "repaired_solution": "def search_rotated_array(nums: list[int], target: int) -> int:\n    l, r = 0, len(nums) - 1\n    while l <= r:\n        mid = (l + r) // 2\n        if nums[mid] == target: return mid\n        if nums[l] <= nums[mid]:\n            if nums[l] <= target < nums[mid]: r = mid - 1\n            else: l = mid + 1\n        else:\n            if nums[mid] < target <= nums[r]: l = mid + 1\n            else: r = mid - 1\n    return -1",
            "test": "def check(candidate):\n    assert candidate([4, 5, 6, 7, 0, 1, 2], 0) == 4\n    assert candidate([4, 5, 6, 7, 0, 1, 2], 3) == -1\n    assert candidate([1], 0) == -1\n    assert candidate([1], 1) == 0\n    assert candidate([3, 1], 1) == 1",
            "test_code": "assert search_rotated_array([4, 5, 6, 7, 0, 1, 2], 0) == 4\nassert search_rotated_array([4, 5, 6, 7, 0, 1, 2], 3) == -1\nassert search_rotated_array([1], 0) == -1\nassert search_rotated_array([1], 1) == 0\nassert search_rotated_array([3, 1], 1) == 1",
            "test_cases": [{"input": "([4, 5, 6, 7, 0, 1, 2], 0)", "expected": "4", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/016",
            "name": "median_of_two_sorted_arrays",
            "entry_point": "median_of_two_sorted_arrays",
            "category": "Searching & Sorting",
            "difficulty": "Hard",
            "prompt": "def median_of_two_sorted_arrays(nums1: list[int], nums2: list[int]) -> float:\n    \"\"\"Finds the median of two sorted arrays.\"\"\"\n",
            "requirement": "Write a python function `median_of_two_sorted_arrays(nums1: list[int], nums2: list[int]) -> float` that returns the median of two sorted arrays.",
            "canonical_solution": "def median_of_two_sorted_arrays(nums1: list[int], nums2: list[int]) -> float:\n    merged = sorted(nums1 + nums2)\n    n = len(merged)\n    if n % 2 == 1: return float(merged[n // 2])\n    return (merged[n // 2 - 1] + merged[n // 2]) / 2.0",
            "constraints": ["0 <= len(nums1), len(nums2) <= 1000", "1 <= len(nums1) + len(nums2)"],
            "expected_output": "Float median value",
            "edge_cases": ["One array empty", "Arrays with odd/even combined length"],
            "common_errors": ["Integer division truncating float median"],
            "error_type": ["type_error", "logical_error"],
            "buggy_solution": "def median_of_two_sorted_arrays(nums1: list[int], nums2: list[int]) -> float:\n    merged = sorted(nums1 + nums2)\n    n = len(merged)\n    # Bug: integer division truncates float result\n    return float(merged[n // 2])",
            "buggy_error": "AssertionError: Fails for even total length (does not average middle two elements)",
            "repair_hint": "If total length is even, average middle two elements (merged[n//2-1] + merged[n//2]) / 2.0.",
            "repaired_solution": "def median_of_two_sorted_arrays(nums1: list[int], nums2: list[int]) -> float:\n    merged = sorted(nums1 + nums2)\n    n = len(merged)\n    if n % 2 == 1: return float(merged[n // 2])\n    return (merged[n // 2 - 1] + merged[n // 2]) / 2.0",
            "test": "def check(candidate):\n    assert candidate([1, 3], [2]) == 2.0\n    assert candidate([1, 2], [3, 4]) == 2.5\n    assert candidate([], [1]) == 1.0\n    assert candidate([2], []) == 2.0",
            "test_code": "assert median_of_two_sorted_arrays([1, 3], [2]) == 2.0\nassert median_of_two_sorted_arrays([1, 2], [3, 4]) == 2.5\nassert median_of_two_sorted_arrays([], [1]) == 1.0\nassert median_of_two_sorted_arrays([2], []) == 2.0",
            "test_cases": [{"input": "([1, 3], [2])", "expected": "2.0", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/017",
            "name": "valid_parentheses",
            "entry_point": "valid_parentheses",
            "category": "Data Structures",
            "difficulty": "Easy",
            "prompt": "def valid_parentheses(s: str) -> bool:\n    \"\"\"Checks if bracket sequence is valid and properly matched.\"\"\"\n",
            "requirement": "Write a python function `valid_parentheses(s: str) -> bool` that checks if the input string containing brackets is valid.",
            "canonical_solution": "def valid_parentheses(s: str) -> bool:\n    stack = []\n    mapping = {')': '(', '}': '{', ']': '['}\n    for char in s:\n        if char in mapping:\n            top = stack.pop() if stack else '#'\n            if mapping[char] != top:\n                return False\n        else:\n            stack.append(char)\n    return not stack",
            "constraints": ["0 <= len(s) <= 10^4", "Characters are ()[]{}"],
            "expected_output": "Boolean True if valid, False otherwise",
            "edge_cases": ["Empty string returns True", "Closing bracket without opening", "Odd length returns False"],
            "common_errors": ["Pop from empty stack IndexError when closing bracket appears first"],
            "error_type": ["index_error", "logical_error"],
            "buggy_solution": "def valid_parentheses(s: str) -> bool:\n    stack = []\n    mapping = {')': '(', '}': '{', ']': '['}\n    for char in s:\n        if char in mapping:\n            # Bug: pops without checking if stack is empty\n            if mapping[char] != stack.pop():\n                return False\n        else:\n            stack.append(char)\n    return len(stack) == 0",
            "buggy_error": "IndexError: pop from empty list on input like ')'",
            "repair_hint": "Check if stack is non-empty before popping, or use stack.pop() if stack else '#'.",
            "repaired_solution": "def valid_parentheses(s: str) -> bool:\n    stack = []\n    mapping = {')': '(', '}': '{', ']': '['}\n    for char in s:\n        if char in mapping:\n            top = stack.pop() if stack else '#'\n            if mapping[char] != top:\n                return False\n        else:\n            stack.append(char)\n    return not stack",
            "test": "def check(candidate):\n    assert candidate('()') == True\n    assert candidate('()[]{}') == True\n    assert candidate('(]') == False\n    assert candidate('([)]') == False\n    assert candidate('{[]}') == True\n    assert candidate('') == True\n    assert candidate(']') == False",
            "test_code": "assert valid_parentheses('()') == True\nassert valid_parentheses('()[]{}') == True\nassert valid_parentheses('(]') == False\nassert valid_parentheses('([)]') == False\nassert valid_parentheses('{[]}') == True\nassert valid_parentheses('') == True\nassert valid_parentheses(']') == False",
            "test_cases": [{"input": "()[]{}", "expected": "True", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/018",
            "name": "daily_temperatures",
            "entry_point": "daily_temperatures",
            "category": "Data Structures",
            "difficulty": "Medium",
            "prompt": "def daily_temperatures(temperatures: list[int]) -> list[int]:\n    \"\"\"Monotonic stack: days until a warmer temperature.\"\"\"\n",
            "requirement": "Write a python function `daily_temperatures(temperatures: list[int]) -> list[int]` that returns an array of days to wait for a warmer temperature.",
            "canonical_solution": "def daily_temperatures(temperatures: list[int]) -> list[int]:\n    n = len(temperatures)\n    ans = [0] * n\n    stack = []\n    for i, t in enumerate(temperatures):\n        while stack and temperatures[stack[-1]] < t:\n            prev = stack.pop()\n            ans[prev] = i - prev\n        stack.append(i)\n    return ans",
            "constraints": ["1 <= len(temperatures) <= 10^5"],
            "expected_output": "List of waiting days",
            "edge_cases": ["Strictly decreasing temperatures return all zeroes", "Single element returns [0]"],
            "common_errors": ["Storing temperature values instead of indices on the stack"],
            "error_type": ["logical_error"],
            "buggy_solution": "def daily_temperatures(temperatures: list[int]) -> list[int]:\n    # Bug: stores temperature value instead of index\n    ans = [0] * len(temperatures)\n    stack = []\n    for i, t in enumerate(temperatures):\n        while stack and stack[-1] < t:\n            prev = stack.pop()\n            ans[prev] = 1\n        stack.append(t)\n    return ans",
            "buggy_error": "IndexError / TypeError: using temperature values as list indices",
            "repair_hint": "Store index i in stack so you can compute days difference i - prev.",
            "repaired_solution": "def daily_temperatures(temperatures: list[int]) -> list[int]:\n    n = len(temperatures)\n    ans = [0] * n\n    stack = []\n    for i, t in enumerate(temperatures):\n        while stack and temperatures[stack[-1]] < t:\n            prev = stack.pop()\n            ans[prev] = i - prev\n        stack.append(i)\n    return ans",
            "test": "def check(candidate):\n    assert candidate([73, 74, 75, 71, 69, 72, 76, 73]) == [1, 1, 4, 2, 1, 1, 0, 0]\n    assert candidate([30, 40, 50, 60]) == [1, 1, 1, 0]\n    assert candidate([30, 60, 90]) == [1, 1, 0]\n    assert candidate([90, 80, 70]) == [0, 0, 0]",
            "test_code": "assert daily_temperatures([73, 74, 75, 71, 69, 72, 76, 73]) == [1, 1, 4, 2, 1, 1, 0, 0]\nassert daily_temperatures([30, 40, 50, 60]) == [1, 1, 1, 0]\nassert daily_temperatures([30, 60, 90]) == [1, 1, 0]\nassert daily_temperatures([90, 80, 70]) == [0, 0, 0]",
            "test_cases": [{"input": "[73, 74, 75, 71, 69, 72, 76, 73]", "expected": "[1, 1, 4, 2, 1, 1, 0, 0]", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/019",
            "name": "climb_stairs",
            "entry_point": "climb_stairs",
            "category": "Dynamic Programming",
            "difficulty": "Easy",
            "prompt": "def climb_stairs(n: int) -> int:\n    \"\"\"Distinct ways to climb n steps taking 1 or 2 steps at a time.\"\"\"\n",
            "requirement": "Write a python function `climb_stairs(n: int) -> int` that returns distinct ways to climb a staircase of n steps taking 1 or 2 steps each stride.",
            "canonical_solution": "def climb_stairs(n: int) -> int:\n    if n <= 2: return n\n    a, b = 1, 2\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    return b",
            "constraints": ["1 <= n <= 45"],
            "expected_output": "Integer count of ways",
            "edge_cases": ["n = 1 returns 1", "n = 2 returns 2"],
            "common_errors": ["Exponential unmemoized recursion timeout"],
            "error_type": ["runtime_error"],
            "buggy_solution": "def climb_stairs(n: int) -> int:\n    # Bug: returns 0 for n=1\n    if n == 0: return 0\n    if n == 1: return 0\n    return climb_stairs(n-1) + climb_stairs(n-2)",
            "buggy_error": "AssertionError: climb_stairs(1) returned 0 instead of 1",
            "repair_hint": "Base cases should be if n <= 2: return n.",
            "repaired_solution": "def climb_stairs(n: int) -> int:\n    if n <= 2: return n\n    a, b = 1, 2\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    return b",
            "test": "def check(candidate):\n    assert candidate(1) == 1\n    assert candidate(2) == 2\n    assert candidate(3) == 3\n    assert candidate(5) == 8\n    assert candidate(10) == 89",
            "test_code": "assert climb_stairs(1) == 1\nassert climb_stairs(2) == 2\nassert climb_stairs(3) == 3\nassert climb_stairs(5) == 8\nassert climb_stairs(10) == 89",
            "test_cases": [{"input": "5", "expected": "8", "type": "normal"}]
        },
        {
            "task_id": "CUSTOM/020",
            "name": "coin_change",
            "entry_point": "coin_change",
            "category": "Dynamic Programming",
            "difficulty": "Hard",
            "prompt": "def coin_change(coins: list[int], amount: int) -> int:\n    \"\"\"Fewest coins needed to make up amount, or -1 if impossible.\"\"\"\n",
            "requirement": "Write a python function `coin_change(coins: list[int], amount: int) -> int` that computes fewest number of coins needed to make up amount.",
            "canonical_solution": "def coin_change(coins: list[int], amount: int) -> int:\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for x in range(coin, amount + 1):\n            dp[x] = min(dp[x], dp[x - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1",
            "constraints": ["1 <= len(coins) <= 12", "0 <= amount <= 10^4"],
            "expected_output": "Fewest count of coins or -1",
            "edge_cases": ["amount == 0 returns 0", "impossible amount returns -1"],
            "common_errors": ["Greedy approach fails for non-canonical coin denominations"],
            "error_type": ["logical_error"],
            "buggy_solution": "def coin_change(coins: list[int], amount: int) -> int:\n    # Bug: greedy choice fails on coins like [1, 3, 4] for amount 6 (greedy chooses 4+1+1=3 instead of 3+3=2)\n    coins.sort(reverse=True)\n    count = 0\n    for c in coins:\n        count += amount // c\n        amount %= c\n    return count if amount == 0 else -1",
            "buggy_error": "AssertionError: Greedy solution selects suboptimal coin combination",
            "repair_hint": "Use dynamic programming table dp[x] = min(dp[x], dp[x - coin] + 1) initialized to infinity.",
            "repaired_solution": "def coin_change(coins: list[int], amount: int) -> int:\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for coin in coins:\n        for x in range(coin, amount + 1):\n            dp[x] = min(dp[x], dp[x - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1",
            "test": "def check(candidate):\n    assert candidate([1, 2, 5], 11) == 3\n    assert candidate([2], 3) == -1\n    assert candidate([1], 0) == 0\n    assert candidate([2, 5, 10, 1], 27) == 4\n    assert candidate([186, 419, 83, 408], 6249) == 20",
            "test_code": "assert coin_change([1, 2, 5], 11) == 3\nassert coin_change([2], 3) == -1\nassert coin_change([1], 0) == 0\nassert coin_change([2, 5, 10, 1], 27) == 4\nassert coin_change([186, 419, 83, 408], 6249) == 20",
            "test_cases": [{"input": "coins=[1, 2, 5], amount=11", "expected": "3", "type": "normal"}, {"input": "coins=[2], amount=3", "expected": "-1", "type": "impossible"}]
        }
    ]

def get_all_custom_problems() -> List[Dict[str, Any]]:
    """Combines the base 20 benchmark problems with the 45 extended problems (65 total)."""
    from training.custom_problems_extended import get_additional_custom_problems
    base = get_base_twenty_problems()
    extended = get_additional_custom_problems()
    return base + extended

